.github/workflows/publish_gradle_docker.yml, .github/workflows/publish_python_docker.yml, .github/workflows/publish_python_package.yml, .github/workflows/publish_vanilla_docker.yml, .github/workflows/publish_yarn_docker.yml, .github/workflows/test_gradle_docker.yml, .github/workflows/test_python_docker.yml, .github/workflows/test_python_package.yml, .github/workflows/test_vanilla_docker.yml, .github/workflows/test_yarn_docker.yml, CONTRIBUTING.md, README.md, actions/gradle_checkstyle/action.yml, actions/semantic_versioning/action.yml
This PR:
1. introduces the `is_latest` variable, which indicates if a version is semantically latest compared to the latest git tag; useful for docker tagging.
2. fixes docker tags logic: latest will be added only for the latest release build; add "development" tag for images built from "development" branch
=> Fix: Fix docker tags

.github/workflows/publish_gradle_docker.yml, .github/workflows/publish_python_docker.yml, .github/workflows/publish_python_package.yml, .github/workflows/publish_vanilla_docker.yml, .github/workflows/publish_yarn_docker.yml, .github/workflows/test_gradle_docker.yml, .github/workflows/test_python_docker.yml, .github/workflows/test_python_package.yml, .github/workflows/test_vanilla_docker.yml, .github/workflows/test_yarn_docker.yml, README.md, actions/gradle_checkstyle/action.yml, actions/prepare_node/action.yml
Use lts version for nodejs which is stable and should be available in setup-node action manifest to prevent downloading from NodeJS official website
I'm trying to fix this issue - https://github.com/epam/ai-dial-chat/actions/runs/6667996296/job/18122596624#step:8:99
=> fix: use lts version for nodejs

.github/workflows/publish_gradle_docker.yml, .github/workflows/publish_python_docker.yml, .github/workflows/publish_python_package.yml, .github/workflows/publish_vanilla_docker.yml, .github/workflows/publish_yarn_docker.yml, .github/workflows/test_gradle_docker.yml, .github/workflows/test_python_docker.yml, .github/workflows/test_python_package.yml, .github/workflows/test_vanilla_docker.yml, .github/workflows/test_yarn_docker.yml, README.md, actions/generate_release_notes/action.yml, actions/gradle_checkstyle/action.yml, actions/publish_tag_release/action.yml, actions/semantic_versioning/action.yml
This PR:
- fixes a commit scope the script uses while running on a `release-*`  branch without any tags
- adds unique commits filter
- adds `[skip ci] Update version` filter
=> fix: proper release notes generation

.github/workflows/publish_yarn_docker.yml, .github/workflows/test_yarn_docker.yml
According to docs `npm ci` should be used in automated environments such as test platforms, continuous integration, and deployment
https://docs.npmjs.com/cli/v10/commands/npm-ci
=> fix: use npm ci in github worflows

.github/workflows/python_package_test.yml
Recently Twine has updated their version to `5.1.1`:
https://github.com/pypa/twine/pull/1114
Which contained this line in `pyproject`
```
"pkginfo < 1.11",
```
This line breaks our CI, since poetry uses `pkginfo==1.11`
https://github.com/epam/ai-dial-sdk/actions/runs/9739951082/job/26876106056?pr=108
And somehow `3.10` version of Python can't handle that correctly
Currently Twine is working on fix: https://github.com/pypa/twine/pull/1123/files
But meanwhile, let's just fixate twine on version `5.1.0`
=> fix: fixate twine version in CI

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/generic_docker_test.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml
Even fixating twine at `5.1.0` causes some bugs 
```
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/twine/__init__.py", line 40, in <module>
__uri__ = metadata["home-page"]
~~~~~~~~^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
raise KeyError(item)
KeyError: 'home-page'
```
Latest working [version](https://github.com/epam/ai-dial-sdk/actions/runs/9681634405/job/26712670753) of twine in pipeline was `5.0.0`, let's fixate it for now on this version
=> fix: downgrade twine to 5.0.0

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/generic_docker_test.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml
`ubuntu-latest` currently resolves to `24.04` which has python 3.12 by default and breaks `pip install` system-wide packages commands, e.g. `pip install poetry`
Solutions are:
1. use venv
2. use setup-python with python <=3.11 BEFORE installing packages
3. pin runner OS version to Ubuntu 22.04
Right now, we decided to proceed with a solution no. 3
https://github.com/actions/runner-images/issues/10636
=> chore: pin ubuntu version for python

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/generic_docker_test.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/pr-title-check.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, actions/build_docker/action.yml, actions/generate_release_notes/action.yml, actions/semantic_versioning/action.yml
The change is to support different build.gradle file formats, e.g. all these cases should be supported
```groovy
version = "1.0.0"
```
```groovy
allprojects
{
version = '1.0.0'
}
```
```groovy
allprojects {
version                          =     'huh'   # hello
}
```
=> fix: build.gradle version string regex to support formatting differences

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, .pre-commit-config.yaml, actions/python_prepare/action.yml
Poetry 2.0.0 was released recently: https://github.com/python-poetry/poetry/releases/tag/2.0.0
`pip install poetry` in CI scripts installs the latest version.
Poetry 2.0.0 deprecates certain features from v1, so our Python projects are failing on CI during the sanity check with the deprecation warnings:
https://github.com/epam/ai-dial-sdk/actions/runs/12671721403/job/35314091486?pr=204#step:4:113
```
> poetry check --lock
Warning: [tool.poetry.name] is deprecated. Use [project.name] instead.
Warning: [tool.poetry.version] is set but 'version' is not in [project.dynamic]. If it is static use [project.version]. If it is dynamic, add 'version' to [project.dynamic].
If you want to set the version dynamically via `poetry build --local-version` or you are using a plugin, which sets the version …
```
=> feat: parametrize poetry version and default it to 1.8.5

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, actions/build_docker/action.yml, actions/java_prepare/action.yml
- #141
- #140
- #138
- #137
- #135
=> feat: bump actions versions

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/generic_docker_test.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, actions/generate_release_notes/action.yml, actions/semantic_versioning/action.yml, update-self-dependencies.sh
What:
- remove `persist-credentials: false` option from checkout action invocations
Motivation:
- The current approach not working perfectly on private projects, e.g.
- Additional testing is needed to add `persist-credentials: false` with awareness of private projects, caches, etc.
=> fix: remove persist-credentials option from checkout actions

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .gitignore, SECURITY.md
Add files, such as issue templates, as examples of how to comply with basic community standards
=> chore: add missing files for recommended community standards compliance

actions/generate_release_notes/action.yml, actions/semantic_versioning/action.yml
There's a bug in actions/checkout, where all subsequent checkouts within single job with `lfs: true`.
It doesn't actually fetch LFS files. So, we have to use lfs even we don't need it here.
See https://github.com/actions/checkout/issues/270
=> hotfix: enable LFS support in generate_release_notes action to fix subsequent checkouts

README.md
Use `dataaxiom/ghcr-cleanup-action` action to properly cleanup untagged multi-arch images in GHCR.
=> fix: untagged multi-arch images cleanup

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, actions/build_docker/action.yml
**Added:** option to override 'severity' of vulnerabilities to be displayed in trivy scan results
**Added:** option to override 'limit-severities-for-sarif ' for trivy scans
**Changed:** trivy scan runs in 3 steps: 
- scan produces sarif report with option to display all vulnerabilities (depends on  'limit-severities-for-sarif ' property). will never fail
- uploads sarif report to view it on 'Security' tab
- scans for limited 'severities' and fails if vulnerabilities found and continue_on_error is false
=> feat: improves trivy configuration for all release workflows

.github/workflows/java_dependency_review.yml
- fixes #
- replace `marocchino/sticky-pull-request-comment` with `peter-evans/create-or-update-comment` action for posting a comment in java dependency review workflow 
Original action does not support comment body input from file, which is crusual on huge comments, such as OpenSSF report. If using text input, the `Argument list too long` error occurs.
=> feat: replace action for posting a comment in java dependency review workflow

.github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/generic_docker_test.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml
- fixes #
- Add a feature to make `runs-on` overridable through input for most workflows. The default value - `ubuntu-24.04` 
- Fix the Python package code_checks issue when Twine is installed system-wide and its dependencies conflict with app dependencies, by creating a separate venv.
=> feat: pin runner tag to ubuntu-24.04 with ability to change via workflow input

.github/workflows/deploy-review-command.yml, .github/workflows/gh-e2e-test.yml
- fixes #245 
Configure 1 hour as timeout for `e2e-test/chat` and `e2e-test/overlay` jobs.
=> fix: set 1 hour as timeout for E2E tests

.github/workflows/deploy-review-command.yml
- fixes #243 
Add link to workflow run in the beginning of `/deploy-review` command comment.
=> fix: add workflow run link in the beginning (closes #243)

.github/workflows/deploy-review-command.yml, .github/workflows/e2e-test.yml, .github/workflows/generic_docker_pr.yml, .github/workflows/generic_docker_release.yml, .github/workflows/java_dependency_review.yml, .github/workflows/java_pr.yml, .github/workflows/java_release.yml, .github/workflows/java_test.yml, .github/workflows/node_pr.yml, .github/workflows/node_release.yml, .github/workflows/node_test.yml, .github/workflows/python_docker_pr.yml, .github/workflows/python_docker_release.yml, .github/workflows/python_docker_test.yml, .github/workflows/python_package_pr.yml, .github/workflows/python_package_release.yml, .github/workflows/python_package_test.yml, README.md, actions/build_docker/action.yml
- fixes #
Add ability for independent choice of output artifacts: container image, npm package, or both (default) via `docker-build-enabled` and `publish-enabled` inputs, respectively, for node workflows. Set variable values to match your needs.
=> feat: allow independent choice of output artifacts for node workflows
